"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.timestamp_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class GetNoteRequest(google.protobuf.message.Message):
    """Request for getting a note by id"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    id: builtins.int
    def __init__(
        self,
        *,
        id: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["id", b"id"]) -> None: ...

Global___GetNoteRequest: typing_extensions.TypeAlias = GetNoteRequest

@typing.final
class GetSearchNotesRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _SearchType:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _SearchTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[GetSearchNotesRequest._SearchType.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        Undefined: GetSearchNotesRequest._SearchType.ValueType  # 0
        """default"""
        NoSearch: GetSearchNotesRequest._SearchType.ValueType  # 1
        """just"""
        FullTextTitle: GetSearchNotesRequest._SearchType.ValueType  # 2
        """exact match search"""
        Fuzzy: GetSearchNotesRequest._SearchType.ValueType  # 3
        """typo tolerant search"""
        Context: GetSearchNotesRequest._SearchType.ValueType  # 4
        """semantic search using embeddings"""

    class SearchType(_SearchType, metaclass=_SearchTypeEnumTypeWrapper): ...
    Undefined: GetSearchNotesRequest.SearchType.ValueType  # 0
    """default"""
    NoSearch: GetSearchNotesRequest.SearchType.ValueType  # 1
    """just"""
    FullTextTitle: GetSearchNotesRequest.SearchType.ValueType  # 2
    """exact match search"""
    Fuzzy: GetSearchNotesRequest.SearchType.ValueType  # 3
    """typo tolerant search"""
    Context: GetSearchNotesRequest.SearchType.ValueType  # 4
    """semantic search using embeddings"""

    SEARCH_TYPE_FIELD_NUMBER: builtins.int
    QUERY_FIELD_NUMBER: builtins.int
    LIMIT_FIELD_NUMBER: builtins.int
    OFFSET_FIELD_NUMBER: builtins.int
    search_type: Global___GetSearchNotesRequest.SearchType.ValueType
    """Search parameters"""
    query: builtins.str
    limit: builtins.int
    """Pagination"""
    offset: builtins.int
    def __init__(
        self,
        *,
        search_type: Global___GetSearchNotesRequest.SearchType.ValueType = ...,
        query: builtins.str = ...,
        limit: builtins.int = ...,
        offset: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["limit", b"limit", "offset", b"offset", "query", b"query", "search_type", b"search_type"]) -> None: ...

Global___GetSearchNotesRequest: typing_extensions.TypeAlias = GetSearchNotesRequest

@typing.final
class MinimalNote(google.protobuf.message.Message):
    """Response: represents a minimal Note for search results"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    TITLE_FIELD_NUMBER: builtins.int
    AUTHOR_ID_FIELD_NUMBER: builtins.int
    UPDATED_AT_FIELD_NUMBER: builtins.int
    STRIPPED_CONTENT_FIELD_NUMBER: builtins.int
    id: builtins.int
    title: builtins.str
    author_id: builtins.int
    stripped_content: builtins.str
    @property
    def updated_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        id: builtins.int = ...,
        title: builtins.str = ...,
        author_id: builtins.int = ...,
        updated_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        stripped_content: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["updated_at", b"updated_at"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["author_id", b"author_id", "id", b"id", "stripped_content", b"stripped_content", "title", b"title", "updated_at", b"updated_at"]) -> None: ...

Global___MinimalNote: typing_extensions.TypeAlias = MinimalNote

@typing.final
class Note(google.protobuf.message.Message):
    """Response: represents a Note"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    TITLE_FIELD_NUMBER: builtins.int
    CONTENT_FIELD_NUMBER: builtins.int
    UPDATED_AT_FIELD_NUMBER: builtins.int
    AUTHOR_ID_FIELD_NUMBER: builtins.int
    PERMISSIONS_FIELD_NUMBER: builtins.int
    id: builtins.int
    title: builtins.str
    content: builtins.str
    author_id: builtins.int
    @property
    def updated_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def permissions(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___NotePermission]:
        """repeated NoteEmbedding embeddings = 6;"""

    def __init__(
        self,
        *,
        id: builtins.int = ...,
        title: builtins.str = ...,
        content: builtins.str = ...,
        updated_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        author_id: builtins.int = ...,
        permissions: collections.abc.Iterable[Global___NotePermission] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["updated_at", b"updated_at"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["author_id", b"author_id", "content", b"content", "id", b"id", "permissions", b"permissions", "title", b"title", "updated_at", b"updated_at"]) -> None: ...

Global___Note: typing_extensions.TypeAlias = Note

@typing.final
class NoteEmbedding(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MODEL_FIELD_NUMBER: builtins.int
    EMBEDDING_FIELD_NUMBER: builtins.int
    model: builtins.str
    @property
    def embedding(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
    def __init__(
        self,
        *,
        model: builtins.str = ...,
        embedding: collections.abc.Iterable[builtins.float] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["embedding", b"embedding", "model", b"model"]) -> None: ...

Global___NoteEmbedding: typing_extensions.TypeAlias = NoteEmbedding

@typing.final
class NotePermission(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ROLE_ID_FIELD_NUMBER: builtins.int
    role_id: builtins.int
    def __init__(
        self,
        *,
        role_id: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["role_id", b"role_id"]) -> None: ...

Global___NotePermission: typing_extensions.TypeAlias = NotePermission

@typing.final
class PostNoteRequest(google.protobuf.message.Message):
    """Request to add/Update a note"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TITLE_FIELD_NUMBER: builtins.int
    CONTENT_FIELD_NUMBER: builtins.int
    AUTHOR_ID_FIELD_NUMBER: builtins.int
    title: builtins.str
    content: builtins.str
    author_id: builtins.int
    def __init__(
        self,
        *,
        title: builtins.str = ...,
        content: builtins.str | None = ...,
        author_id: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_content", b"_content", "content", b"content"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_content", b"_content", "author_id", b"author_id", "content", b"content", "title", b"title"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_content", b"_content"]) -> typing.Literal["content"] | None: ...

Global___PostNoteRequest: typing_extensions.TypeAlias = PostNoteRequest

@typing.final
class AlterNoteRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    TITLE_FIELD_NUMBER: builtins.int
    CONTENT_FIELD_NUMBER: builtins.int
    AUTHOR_ID_FIELD_NUMBER: builtins.int
    id: builtins.int
    title: builtins.str
    content: builtins.str
    author_id: builtins.int
    def __init__(
        self,
        *,
        id: builtins.int = ...,
        title: builtins.str | None = ...,
        content: builtins.str | None = ...,
        author_id: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_author_id", b"_author_id", "_content", b"_content", "_title", b"_title", "author_id", b"author_id", "content", b"content", "title", b"title"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_author_id", b"_author_id", "_content", b"_content", "_title", b"_title", "author_id", b"author_id", "content", b"content", "id", b"id", "title", b"title"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_author_id", b"_author_id"]) -> typing.Literal["author_id"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_content", b"_content"]) -> typing.Literal["content"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_title", b"_title"]) -> typing.Literal["title"] | None: ...

Global___AlterNoteRequest: typing_extensions.TypeAlias = AlterNoteRequest
