# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc_mod/proto/note.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'grpc_mod/proto/note.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19grpc_mod/proto/note.proto\x12\x04note\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\x1c\n\x0eGetNoteRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"\xc9\x01\n\x04Note\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12.\n\nupdated_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x11\n\tauthor_id\x18\x05 \x01(\x05\x12\'\n\nembeddings\x18\x06 \x03(\x0b\x32\x13.note.NoteEmbedding\x12)\n\x0bpermissions\x18\x07 \x03(\x0b\x32\x14.note.NotePermission\"1\n\rNoteEmbedding\x12\r\n\x05model\x18\x01 \x01(\t\x12\x11\n\tembedding\x18\x02 \x03(\x02\"!\n\x0eNotePermission\x12\x0f\n\x07role_id\x18\x01 \x01(\x05\"\xb5\x01\n\x0fPostNoteRequest\x12,\n\x02id\x18\x01 \x01(\x0b\x32\x1b.google.protobuf.Int32ValueH\x00\x88\x01\x01\x12+\n\x05title\x18\x02 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12-\n\x07\x63ontent\x18\x03 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x11\n\tauthor_id\x18\x04 \x01(\x05\x42\x05\n\x03_id2i\n\x0bNoteService\x12+\n\x07GetNote\x12\x14.note.GetNoteRequest\x1a\n.note.Note\x12-\n\x08PostNote\x12\x15.note.PostNoteRequest\x1a\n.note.Noteb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_mod.proto.note_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETNOTEREQUEST']._serialized_start=100
  _globals['_GETNOTEREQUEST']._serialized_end=128
  _globals['_NOTE']._serialized_start=131
  _globals['_NOTE']._serialized_end=332
  _globals['_NOTEEMBEDDING']._serialized_start=334
  _globals['_NOTEEMBEDDING']._serialized_end=383
  _globals['_NOTEPERMISSION']._serialized_start=385
  _globals['_NOTEPERMISSION']._serialized_end=418
  _globals['_POSTNOTEREQUEST']._serialized_start=421
  _globals['_POSTNOTEREQUEST']._serialized_end=602
  _globals['_NOTESERVICE']._serialized_start=604
  _globals['_NOTESERVICE']._serialized_end=709
# @@protoc_insertion_point(module_scope)
